Repository Dev-FE-1/Toy_Project_2_Team1, pull requests merged in 2024-08, with the labels that each got.

#67 [feat] firebase 유저정보 연동
  src/api/User.ts
  src/api/index.ts
  src/types/type.ts
Labels: 📬 API

#71 [feat] Calendar 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarToolbar.tsx
  src/components/Calendar/DateCellWrapper.tsx
  src/pages/Schedule.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/calendar.d.ts
Labels: ✨ Feature

#74 [design] 공통 레이아웃 최대 넓이 및 디자인 수정
  src/assets/images/money.png
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarToolbar.tsx
  src/components/Calendar/DateCellWrapper.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Tabs.tsx
  src/components/dashboard/PayrollList.tsx
  src/components/dashboard/PayrollNotice.tsx
  src/components/layout/Navbar.tsx
  src/layouts/Root.tsx
  src/pages/Profile.tsx
  src/pages/Salary.tsx
  src/pages/Schedule.tsx
  src/styles/GlobalStyle.tsx
  src/types/global.d.ts
Labels: 🎨 Html&css

#76 [feat] 동료이벤트 컴포넌트 제작
  src/assets/image/user_default.svg
  src/components/dashboard/UpcomingSchdules.tsx
  src/types/props.ts
  src/types/type.ts
Labels: ✨ Feature

#80 [feat] Schedule Reducer 생성 및 firebase로 실제 데이터 불러오기
  package-lock.json
  src/components/Calendar/Calendar.tsx
  src/components/common/Tabs.tsx
  src/constants/colors.ts
  src/hooks/useFetchSchedule.ts
  src/pages/Schedule.tsx
  src/store/hooks.ts
  src/store/reducer/scheduleSlice.ts
  src/store/store.ts
  src/styles/GlobalStyle.tsx
  src/types/api.ts
  src/types/schedule.ts
  src/utils/schedule.ts
Labels: ✨ Feature

#84 [refactor] 컴포넌트 사용성 개선
  src/components/common/Buttons/Button.tsx
  src/components/common/Input.tsx
Labels: 🔨 Refactor

#85 [feat] 프로필 페이지 UI 구현
  .gitmessage.txt
  src/pages/Profile.tsx
Labels: ✨ Feature

#86 [feat] Home 페이지에 컴포넌트 추가
  src/components/dashboard/PayrollList.tsx
  src/components/dashboard/PayrollNotice.tsx
  src/components/dashboard/UpcomingSchdules.tsx
  src/components/dashboard/UpcomingSchedules.tsx
  src/pages/Home.tsx
Labels: ✨ Feature

#81 [feat] 급여명세서 상세 컴포넌트 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/payroll/PayrollList.tsx
  src/constants/path.ts
  src/pages/PayrollDetail.tsx
  src/pages/Salary.tsx
Labels: ✨ Feature

#90 [fix] 라우터 오류 수정
  src/App.tsx
  src/constants/path.ts
  src/pages/PayrollDetail.tsx
Labels: 🐞 BugFix

#91 [design] Profile 페이지 스타일 수정
  src/pages/Profile.tsx
Labels: 🎨 Html&css

#94 [feat] 오늘의 일정 컴포넌트 구현
  src/components/daySchedule/DaySchedule.tsx
  src/pages/Schedule.tsx
Labels: ✨ Feature

#103 [fix] 파일명 대소문자 오류 수정
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarToolbar.tsx
  src/components/Calendar/DateCellWrapper.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/IconTextButton.tsx
Labels: 🐞 BugFix

#107 [refactor] 오늘의 일정 컴포넌트 리팩토링
  src/components/dailySchedule/DailySchedule.tsx
  src/components/daySchedule/DaySchedule.tsx
  src/pages/Schedule.tsx
  src/utils/dailySchedule.ts
Labels: 🔨 Refactor

#115 [feat] 스케줄 추가/수정 페이지 추가
  src/App.tsx
  src/components/common/Select.tsx
  src/components/common/ToggleSwitch.tsx
  src/components/common/buttons/Button.tsx
  src/components/scheduleForm/ColorPicker.tsx
  src/components/scheduleForm/ScheduleForm.tsx
  src/constants/colors.ts
  src/constants/path.ts
  src/pages/Schedule.tsx
  src/pages/ScheduleAdd.tsx
  src/pages/ScheduleEdit.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/schedule.ts
Labels: ✨ Feature

#117 [feat] 로고 추가
  src/assets/images/logo.svg
  src/assets/images/logo_icon.svg
  src/components/dashboard/UpcomingSchedules.tsx
  src/pages/Home.tsx
  src/pages/SignIn.tsx
Labels: ✨ Feature

#110 [feat] 정정 신청 내역 컴포넌트 추가
  src/App.tsx
  src/components/dashboard/PayrollNotice.tsx
  src/components/payroll/CorrectionHistory.tsx
  src/constants/path.ts
  src/pages/Salary.tsx
Labels: ✨ Feature

#118 [feat] 일정 상세페이지 추가
  src/App.tsx
  src/components/common/Modal.tsx
  src/components/common/buttons/IconTextButton.tsx
  src/components/dailySchedule/DailySchedule.tsx
  src/constants/path.ts
  src/pages/DailyScheduleDetail.tsx
  src/utils/dailySchedule.ts
Labels: ✨ Feature

#122 [refactor] 로그인 페이지 기능개선
  src/App.tsx
  src/api/Auth.ts
  src/constants/signIn.ts
  src/pages/SignIn.tsx
  src/store/reducer/authSlice.ts
  src/types/api.ts
  src/types/props.d.ts
  src/types/type.d.ts
  src/utils/auth.ts
Labels: 🔨 Refactor

#125 [design] 파비콘 추가
  index.html
  src/assets/images/favicon/android-chrome-192x192.png
  src/assets/images/favicon/android-chrome-512x512.png
  src/assets/images/favicon/apple-touch-icon.png
  src/assets/images/favicon/favicon-16x16.png
  src/assets/images/favicon/favicon-32x32.png
  src/assets/images/favicon/favicon.ico
  src/assets/images/favicon/favicon.png
  src/assets/images/favicon/favicon.svg
  src/assets/images/favicon/safari-pinned-tab.svg
  src/assets/manifest.json
Labels: 🥰 Accessibility, 🎨 Html&css

#126 [fix] 파일명 변경, 경로 수정
  src/api/auth.ts
  src/api/index.ts
  src/api/user.ts
  src/components/common/Modal.tsx
  src/components/common/buttons/Button.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/store/reducer/authSlice.ts
  src/styles/theme.ts
  src/types/api.d.ts
  src/types/calendar.d.ts
  src/types/schedule.d.ts
  src/utils/validators.ts
Labels: 🔨 Refactor, 🐞 BugFix

#130 [feat] 일정 삭제하기
  src/pages/DailyScheduleDetail.tsx
  src/pages/Schedule.tsx
  src/store/reducer/scheduleSlice.ts
  src/types/calendar.d.ts
  src/types/schedule.d.ts
Labels: ✨ Feature

#132 [feat] 토스트메세지 커스텀 훅 개발
  src/components/common/Toast.tsx
  src/hooks/useToast.ts
  src/layouts/Root.tsx
  src/store/reducer/toastSlice.ts
  src/store/store.ts
  src/types/api.d.ts
Labels: ✨ Feature

#135 [fix] userNo를 이용한 일정 조회
  src/pages/DailyScheduleDetail.tsx
  src/store/reducer/scheduleSlice.ts
Labels: 🐞 BugFix

#138 [feat] DatePicker, TimePicker 추가
  src/components/common/DatePicker.tsx
  src/components/common/TimePicker.tsx
  src/components/scheduleForm/ScheduleForm.tsx
  src/hooks/useFetchSchedule.ts
  src/hooks/useOnClickOutside.ts
  src/store/reducer/scheduleSlice.ts
  src/utils/calendar.ts
  src/utils/time.ts
Labels: ✨ Feature

#140 [design] 로그인 페이지 스타일 수정
  src/components/common/Input.tsx
  src/components/common/Spinner.tsx
  src/pages/SignIn.tsx
Labels: 🎨 Html&css

#143 [design] 급여 페이지 디자인 및 스타일 수정
  src/components/payroll/CorrectionForm.tsx
  src/components/payroll/CorrectionHistory.tsx
  src/components/payroll/PayrollList.tsx
Labels: 🎨 Html&css

#145 [design] schedule 페이지 스타일 수정
  src/components/dailySchedule/DailySchedule.tsx
  src/components/scheduleForm/ScheduleForm.tsx
  src/pages/DailyScheduleDetail.tsx
  src/pages/Schedule.tsx
Labels: 🎨 Html&css

#151 [feat] home 페이지에 오늘의 일정 컴포넌트 추가
  src/components/common/Modal.tsx
  src/components/dashboard/UpcomingSchedules.tsx
  src/pages/Home.tsx
Labels: ✨ Feature

#134 [feat] 정정내역 상세페이지 추가
  src/App.tsx
  src/components/common/Tabs.tsx
  src/components/layout/Header.tsx
  src/components/payroll/CorrectionForm.tsx
  src/components/payroll/CorrectionHistory.tsx
  src/components/payroll/PayrollList.tsx
  src/constants/path.ts
  src/pages/CorrectionDetail.tsx
  src/pages/CorrectionEdit.tsx
  src/pages/PayrollDetail.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Salary.tsx
Labels: ✨ Feature

#149 [Feat] 프로필 페이지 구현 #148
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
Labels: ✨ Feature

#152 [feat] 정정신청 api 연동
  src/api/common.ts
  src/api/payroll.ts
  src/api/schedule.ts
  src/components/common/buttons/IconTextButton.tsx
  src/components/payroll/CorrectionForm.tsx
  src/constants/api.ts
  src/store/reducer/payrollSlice.ts
  src/store/store.ts
  src/types/api.d.ts
  src/types/payroll.d.ts
  src/utils/auth.ts
  src/utils/dailySchedule.ts
Labels: ✨ Feature

#162 [fix] getUID 비동기처리
  src/api/payroll.ts
  src/api/schedule.ts
  src/store/reducer/scheduleSlice.ts
  src/utils/auth.ts
Labels: 🐞 BugFix

#163 [feat] 프로필 UID 연결 (#159)
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
Labels: ✨ Feature

#165 [feat] 404 페이지 추가
  src/pages/NotFound.tsx
Labels: ✨ Feature

#166 [feat] 일정 수정 기능 추가
  src/api/schedule.ts
  src/components/scheduleForm/ScheduleForm.tsx
  src/constants/path.ts
  src/pages/ScheduleEdit.tsx
  src/store/reducer/scheduleSlice.ts
  src/types/schedule.d.ts
  src/utils/schedule.ts
Labels: ✨ Feature

#146 [refactor] 일정 삭제 시 해당 월의 검색범위에서 일정 찾아 삭제
  src/components/dailySchedule/DailySchedule.tsx
  src/pages/DailyScheduleDetail.tsx
  src/store/reducer/scheduleSlice.ts
Labels: 🔨 Refactor

#167 [feat] 정정페이지 완료
  src/api/common.ts
  src/api/payroll.ts
  src/components/common/Toast.tsx
  src/components/payroll/CorrectionForm.tsx
  src/components/payroll/CorrectionHistory.tsx
  src/pages/CorrectionDetail.tsx
  src/pages/CorrectionEdit.tsx
  src/store/reducer/payrollSlice.ts
Labels: ✨ Feature

#170 [design] 전체적인 스타일 수정
  src/components/common/Toast.tsx
  src/components/dashboard/CompanySchedules.tsx
  src/components/payroll/CorrectionForm.tsx
  src/mock/data.ts
  src/pages/CorrectionDetail.tsx
  src/pages/CorrectionEdit.tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/PayrollDetail.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/types/type.d.ts
Labels: 🎨 Html&css

#169 [feat] 급여명세서 api연동
  src/api/payroll.ts
  src/components/payroll/PayrollList.tsx
  src/constants/salary.ts
  src/pages/PayrollDetail.tsx
  src/types/api.d.ts
  src/types/payroll.d.ts
  src/utils/salary.ts
Labels: ✨ Feature

#179 [fix] 하루 종일 일정이 오전12:00-오후11:59로 뜨는 오류 해결
  src/utils/dailySchedule.ts
Labels: 🐞 BugFix
