Repository Dev-FE-1/Toy_Project_2_Team1, pull requests merged in 2024-07, with the labels that each got.

#21 [fix] husky와 eslint, prettier 충돌 오류 해결
  . prettierrc.yml
  .eslintignore
  .eslintrc.cjs
  .prettierignore
  eslint.config.js
  src/main.tsx
  vite.config.ts
Labels: 🐞 BugFix

#26 [fix] globalFonts 파일명 오류 수정
  package-lock.json
  src/styles/GlobalFonts.ts
  src/styles/globalFonts.ts
Labels: 🐞 BugFix

#31 [fix] eslint 윈도우os 오류 수정 #30
  .eslintrc.cjs
  .prettierrc.cjs
Labels: ⚙ Setting

#33 [fix] import 절대경로 오류 수정
  .eslintrc.cjs
  src/App.tsx
Labels: 🐞 BugFix

#34 [feat] Navbar component 추가
  package-lock.json
  package.json
  src/components/layout/Navbar.tsx
  src/layouts/Root.tsx
  src/styles/theme.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨ Feature

#35 feat: 기본 Button 컴포넌트 추가
  src/components/common/Button.tsx
Labels: ✨ Feature

#36 [feat] Select 컴포넌트 추가
  package-lock.json
  package.json
  src/components/common/Select.tsx
Labels: ✨ Feature

#38 [feat] Badge 컴포넌트 추가
  src/components/common/Badge.tsx
Labels: ✨ Feature

#41 [feat] Header 컴포넌트 추가
  src/components/layout/Header.tsx
Labels: ✨ Feature

#42 [Feat] 텍스트가 있는 아이콘버튼 컴포넌트 추가
  src/components/common/IconButton.tsx
Labels: ✨ Feature

#40 [feat] Toast 컴포넌트 추가
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  package-lock.json
  src/components/common/Toast.tsx
Labels: ✨ Feature

#48 [feat] input 컴포넌트 추가
  src/components/common/Input.tsx
  src/pages/Profile.tsx
Labels: ✨ Feature

#49 [refactor] 컴포넌트 재사용성 향상
  src/components/common/Badge.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/IconTextButton.tsx
  src/components/common/IconButton.tsx
  src/components/common/Toast.tsx
  src/styles/theme.ts
  src/styles/transition.css
Labels: 🔨 Refactor

#59 [refactor] input 컴포넌트 정렬 수정 (#57)
  src/components/common/Input.tsx
Labels: 🎨 Html&css
